<%@ Page Title="" Language="C#" MasterPageFile="~/Views/Shared/Site.Master" Inherits="System.Web.Mvc.ViewPage<System.Collections.Generic.List<HTL.Grieskirchen.VaKEGrade.Database.SchoolClass>>"  %>
<%@ Import Namespace="Trirand.Web.Mvc" %>

<asp:Content ID="Content1" ContentPlaceHolderID="TitleContent" runat="server">
	Index
</asp:Content>

<asp:Content ID="Content3" ContentPlaceHolderID="ScriptContent" runat="server">
    
    
    
	

   <script type="text/javascript">
       var lastPupilSelection;
       var lastSPFSelection;

       $(document).ready(function () {
           jQuery("#pupils").jqGrid({
               url: '/ClassTeacher/RetrieveAllStudents',
               datatype: 'json',
               mtype: 'POST',
               colNames: ['Nachname', 'Vorname', 'Religion', 'Geburtsdatum', 'Geschlecht'],
               colModel: [
               // { name: 'ID', index: 'ID', width: 40, align: 'left', visible: false, editable: false },
                     {name: 'LastName', index: 'LastName', width: 100, align: 'left', editable: true },
                     { name: 'FirstName', index: 'FirstName', width: 100, align: 'left', editable: true },
                     { name: 'Religion', index: 'Religion', width: 100, align: 'left', editable: true },
                     { name: 'Birthdate', index: 'Birthdate', width: 100, align: 'left', editable: true, editoptions: {
                         size: 10, maxlengh: 10,
                         dataInit: function (element) {
                             $(element).datepicker({ dateFormat: 'dd.mm.yy', constrainInput: false, showOn: 'focus', buttonText: '...' });
                         }
                     }
                     },
                     { name: 'Gender', index: 'Gender', width: 100, align: 'left', editable: true, edittype: 'select', editoptions: { value: "m:männlich;w:weiblich"} }
                     ],
               rowNum: 10,
               rowList: [5, 10, 20, 50],
               sortname: 'Id',
               sortorder: 'desc',
               viewrecords: true,
               editurl: '/ClassTeacher/EditStudent',
               pager: '#pupilsPager',
               //imgpath: '/scripts/themes/coffee/images',
               caption: 'Schülerliste',
               autowidth: true,
               onSelectRow: editPupilRow
           }).navGrid('#pupilsPager',null, false, true, true, true, true);
           
       });

       function updateSPFGrid(pupilID) {
           var subjects = $.ajax({ url: '/ClassTeacher/RetrieveAllSubjects', async: false, success: function (data, result) { if (!result) alert('Failure to retrieve the Countries.'); } }).responseText;
           jQuery("#spfs").jqGrid({
               url: '/ClassTeacher/RetrieveSPFs?pupilID='+pupilID,
               datatype: 'json',
               mtype: 'POST',
               colNames: ['Gegenstand', 'Schulstufe'],
               colModel: [
               // { name: 'ID', index: 'ID', width: 40, align: 'left', visible: false, editable: false },
                     {name: 'Subject', index: 'Subject', width: 100, align: 'left', editable: true, edittype: "select", editrules: { required: true }, editoptions: { size: subjects.length} },
                     { name: 'Level', index: 'Level', width: 100, align: 'left', editable: true },
                     ],
               rowNum: 10,
               rowList: [5, 10, 20, 50],
               sortname: 'Id',
               sortorder: 'desc',
               viewrecords: true,
               editurl: '/ClassTeacher/EditSPF',
               //imgpath: '/scripts/themes/coffee/images',
               caption: 'SPFs',
               autowidth: true,
               onSelectRow: editSPFRow,
               loadComplete: function() {
$('#spfs').setColProp('Subject', { editoptions: { value: subjects} });}
           });
       }

       function editPupilRow(id) {
           if (id) {
               var grid = $("#pupils");
               grid.restoreRow(lastPupilSelection);
               grid.editRow(id, true);
               lastPupilSelection = id;
           }
           updateSPFGrid(id);
       }

       function editSPFRow(id) {
           if (id) {
               var grid = $(this);
               grid.restoreRow(lastSPFSelection);
               grid.editRow(id, true, null, null, null, { 'pupilID': lastPupilSelection });
               lastSPFSelection = id;
           }
       }

       function showSPFSubGrid(subgrid_id, row_id) {
           // the "showSubGrid_OrdersGrid" function is autogenerated and available globally on the page by the second child grid. 
           // Calling it will place the child grid below the parent expanded row and will call the action specified by the DaraUrl property
           // of the child grid, with ID equal to the ID of the parent expanded row                
           showSubGrid_SPFGrid(subgrid_id, row_id);
       }             

   </script>

</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">

     




    <h2>Aufgaben:</h2>
  

    

    <div id="accordion">
    <h3><a href="#">Schülerdaten bearbeiten</a></h3>
        
    <div>
           <table id="pupils"></table>
           <table id="spfs"></table>
           <%--<%= Html.Trirand().JQGrid((JQGrid)Session["PupilGModel"], "PupilGrid") %>
           <%= Html.Trirand().JQGrid((JQGrid)Session["SPFGModel"], "SPFGrid") %>--%>
    </div>
     <div id="pupilsPager"></div>
    <h3><a href="#">Schüler benoten</a></h3>
    <div id="classes">
    </div>

    <h3><a href="/ClassTeacher/GenerateCertificates">Zeugnisse drucken</a></h3>
    <div></div>
    </div>
   
    

    

</asp:Content>
